In [1]:
import db_connection.ihub as ihub
import db_connection.alice as alice
import pandas as pd
import numpy as np
from scipy.stats import norm
import warnings

In [3]:
# dataframe:
df = pd.read_csv('C:\\Users\\mojiway\\Desktop\\recom\\recom_table_2.csv',index_col=None)

In [4]:
df.head()

,hotel_id,city,hotel_name,stars,lat,lon,booking,rns,gbv,gbv_rns
0,242495,Boston,The Godfrey Hotel Boston,4-star,42.354662,-71.061475,107,189,27007,143
1,53230,Marrakech,La Mamounia,5-star,31.621885,-7.997605,5,11,9068,824
2,311703,Nassau,Grand Hyatt At Baha Mar,4-star,25.070796,-77.396624,7,36,8416,234
3,8303,Bangkok,Shangri-La Hotel Bangkok,5-star,13.720692,100.513980,10,30,8151,272
4,8519,Bali,Four Seasons Resort Bali at Sayan,5-star,-8.495717,115.244937,5,18,7877,438

In [9]:
df.drop(['hotel_name','city','stars'], axis=1)

      hotel_id        lat         lon  booking  rns    gbv  gbv_rns
0       242495  42.354662  -71.061475      107  189  27007      143
1        53230  31.621885   -7.997605        5   11   9068      824
2       311703  25.070796  -77.396624        7   36   8416      234
3         8303  13.720692  100.513980       10   30   8151      272
4         8519  -8.495717  115.244937        5   18   7877      438
5       134368  40.739162  -74.027744       17   32   7438      232
6        55850  37.785872 -122.407731       13   38   7267      191
7        67930  40.749943  -73.990941       17   38   6742      177
8          896   7.977388   98.280226        3   15   6524      435
9        64912  21.274273 -157.823954        5   19   6344      334
10      107875  43.748048    7.438787        6   12   6279      523
11      223990  51.504349   -0.086786        3    7   5788      827
12        8930   7.886890   98.292821        2   10   5676      568
13      139958  20.944217 -156.690265        6   26   5650      217
14      186639  21.279865 -157.827829        5   25   5619      225
15         786  13.723229  100.539688        7   21   5219      249
16       59718  26.528610  -82.191929        8   22   4806      218
17      184492  21.142329  -86.773587        2   11   4623      420
18        4817 -37.670662  144.850315       22   22   4457      203
19      231834  40.743856  -73.983789        2    8   4419      552
20       51262  21.277040 -157.830193        3   14   4338      310
21       85777  18.090343  -63.023542        2   12   4121      343
22       92536  48.874500    2.806130       26   42   4085       97
23        8489  -8.782879  115.158604        2    7   4077      582
24       62517  36.142395 -115.156723       30   55   4050       74
25       74441  21.278016 -157.831816        1    5   3983      797
26       54237  26.714776  -80.033964        4    7   3962      566
27       54495  51.498681   -0.137296        8   12   3897      325
28       67588  43.738409    7.426548        4    9   3862      429
29       81993  28.343707  -81.525239        9   15   3784      252
...        ...        ...         ...      ...  ...    ...      ...
1262    103742  59.937605   30.321693        1    1     35       35
1263      5625  -7.499863  110.223624        1    1     35       35
1264     11788  -8.181484  113.687188        1    1     35       35
1265     16163  -6.702686  108.561241        1    1     34       34
1266      3314  -6.986714  110.415188        1    1     34       34
1267     13348  13.728661  100.527137        1    1     33       33
1268    323356  -6.979397  110.414476        1    1     33       33
1269      8928   5.418273  100.319221        1    1     32       32
1270     66800  39.384350  -74.427651        1    1     31       31
1271      7611  13.719814  100.548254        1    1     31       31
1272     13421  -7.295231  112.675237        1    1     30       30
1273      8644  13.753288  100.608485        1    1     29       29
1274      3924  10.768308  106.700610        1    1     29       29
1275     56014  36.133052 -115.084902        1    1     28       28
1276     21561  -6.187226  106.820823        1    1     28       28
1277     12154  13.723866  100.538301        1    1     27       27
1278     22743  -6.125765  106.791613        1    1     27       27
1279      1300  -6.174066  106.811867        1    1     26       26
1280      7159  -6.233231  106.844783        1    1     26       26
1281     15348  14.576839  120.981477        1    1     25       25
1282      3566  13.688863  100.608120        1    1     25       25
1283      5836  -6.149109  106.833209        1    1     25       25
1284     27157  13.713648  100.526789        1    1     23       23
1285    314466  -7.273205  112.748329        1    1     22       22
1286     13855  -5.154637  119.436088        1    1     21       21
1287     17971  13.758373  100.497118        1    1     20       20
1288       417  13.742913  100.601842        1    1     20       20
1289      7099  -7.262138  112.726329        1    1     20       20
1290      5829   3.129240  101.712310        1    1     18       18
1291      7103  -7.561340  110.808957        1    1     18       18

[1292 rows x 7 columns]